import random

# @DESC Method for user to try and guess the random number generated by computer 
def guess(x):
    random_number = random.randint(1,x)
    your_guess = 0
    while your_guess != random_number:
        your_guess = int(input(f"Guess a number between 1 and {x}: "))
        if your_guess < random_number:
            print("Oops, too low.Guess higher")
        elif your_guess > random_number:
            print("Oops, too high.Guess lower")
    
    print(f"Yaasss! You got it! You guessed the number {random_number} ")

# @DESC Method for computer to try and guess the random number generated by user
def machine_guess(x):
    low = 1
    high = x
    user_response = ''

    while user_response != 'C':
        if low != high:
            machine_guess = random.randint(low, high)
        else:
            machine_guess = low #or high, cause they are equal

        user_response = input(f"Is {machine_guess} too high(H) or too low(L) or correct(C)?: ").upper()

        if user_response == 'L':
           low = machine_guess + 1
        elif user_response == 'H':
            high = machine_guess-1

    print(f"Yaaay, your number,{machine_guess} was guessed right by the computer")    

high = int(input("Pick a high bound: "))
machine_guess(high)


# upper_limit = int(input("Enter upper limit of your guess: "))
# guess(upper_limit)